// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSLkFpI_cby_7GaPJXDKQp8v6acoAGlg',
    appId: '1:559721482426:web:3576b79aeed129462d9a83',
    messagingSenderId: '559721482426',
    projectId: 'webrtc-example-1af2b',
    authDomain: 'webrtc-example-1af2b.firebaseapp.com',
    storageBucket: 'webrtc-example-1af2b.appspot.com',
    measurementId: 'G-KQ4Q8WGRJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzXmZJtLW6fIclWa--KlZkUEHHolz49OU',
    appId: '1:559721482426:android:e9123da1e1539cfc2d9a83',
    messagingSenderId: '559721482426',
    projectId: 'webrtc-example-1af2b',
    storageBucket: 'webrtc-example-1af2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIQ5LZAT4z0juZO-FX4SFT4_vJGyhVv4c',
    appId: '1:559721482426:ios:23ad9523daa2502d2d9a83',
    messagingSenderId: '559721482426',
    projectId: 'webrtc-example-1af2b',
    storageBucket: 'webrtc-example-1af2b.appspot.com',
    iosBundleId: 'com.example.webrtcClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIQ5LZAT4z0juZO-FX4SFT4_vJGyhVv4c',
    appId: '1:559721482426:ios:15bfc692a69694c12d9a83',
    messagingSenderId: '559721482426',
    projectId: 'webrtc-example-1af2b',
    storageBucket: 'webrtc-example-1af2b.appspot.com',
    iosBundleId: 'com.example.webrtcClient.RunnerTests',
  );
}
